### creating all the details using many to many association

### Read Metadata 

GET http://localhost:4004/catalog/$metadata

### Read Employee

GET http://localhost:4004/catalog/Employee

### Create

POST http://localhost:4004/catalog/Employee HTTP/1.1
Content-Type: application/json

{ 
    "Fname"     : "Satyajit 2",
    "Lname"     : "Narkhede",
    "EmpGender" : "M",
    "EmpEmail"  : "snarkhede@deloitte.com",
    "EmpSalary" : 3000,
    "Currency_code" : "INR",
    "city_ID"   : 401,
    "task"      : [
        {
            "Id"        : 5,
            "Status"    : "WIP",
            "Desc"      : "Working on UI5 web component"
        },
        {
            "Id"        : 6,
            "Status"    : "Complted",
            "Desc"      : "Working with Hana Cloud"
        }
    ]
}

### Read Employee along with association

GET http://localhost:4004/catalog/Employee?$expand=task


### Hike salary of the employee

POST http://localhost:4004/catalog/hikeSalary
Content-Type: application/json

{
    "employee"  : "1510a94e-fbe6-4c3b-a53f-9a5650b8e4b8",
    "amount"    : 1000.12
}


### Update the currency in Employee table

PATCH http://localhost:4004/catalog/Employee/7b68b404-a80e-4552-adc9-dbd6e5c2ed34
Content-Type: application/json

{
    "EmpSalary"       : 2000,
    "Currency_code"   : "INR"
}


### Calling unBoundedFunc()

GET http://localhost:4004/catalog/unBoundedFunc()